project:
  type: website
  output-dir: docs

website:
  title: "André Wattø Sjuve"
  navbar:
    background: "#124559"
    left:
      - href: index.qmd
        text: Home
      - research.qmd
  page-footer: 
    background: "#124559"
    left: "Copyright 2022, André Wattø Sjuve"
    right: 
      - icon: github
        href: https://github.com/AndreSjuve/
      - icon: envelope
        href: mailto:andre.sjuve@nhh.no

format:
  html:
    theme: 
      dark:  superhero
      light: lux
    css: styles.css
    toc: true



